name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.1
          extensions: none, curl, dom, mbstring, simplexml, tokenizer, xml, xmlwriter, json
          coverage: none

      - run: composer install --no-dev

      - run: git archive --output=tpay-openapi-php.zip HEAD

      - run: zip -ur tpay-openapi-php.zip vendor/

      - uses: softprops/action-gh-release@v1
        with:
          files: tpay-openapi-php.zip
